# Optimized pre-commit configuration
# Catches CI failures before they happen

repos:
  # Stage 1: Fast syntax/import checks (5 seconds)
  - repo: local
    hooks:
      - id: verify-imports
        name: Verify Python imports
        entry: python -m py_compile
        language: system
        files: \.py$
        pass_filenames: true
        
      - id: check-merge-conflicts
        name: Check for merge conflicts
        entry: bash -c 'if grep -r "<<<<<<< \|======= \|>>>>>>> " src/ tests/ --include="*.py" 2>/dev/null; then exit 1; fi'
        language: system
        pass_filenames: false

      - id: pytest-collect
        name: Verify test collection
        entry: bash -c 'pytest --collect-only -q >/dev/null 2>&1 || exit 1'
        language: system
        pass_filenames: false
        stages: [push]

  # Stage 2: Code quality (30 seconds)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Stage 3: Security checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Optional: Run fast tests on push
  - repo: local
    hooks:
      - id: fast-tests
        name: Run fast unit tests
        entry: bash -c 'pytest -m "not slow" --tb=short -x -q || exit 1'
        language: system
        pass_filenames: false
        stages: [push]
        verbose: true