# Pre-commit hooks optimized for Claude Code development environment
# Focus on automated fixes and critical checks only

repos:
  # Basic file hygiene (automated fixes)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: deployment/
      - id: check-toml
      - id: debug-statements  # Catch forgotten breakpoints

  # Code formatting (automated)
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.12
        args: [--line-length=100]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # Type checking (critical for recommendation accuracy)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies:
          - types-pytz
          - pandas-stubs
          - numpy

  - repo: local
    hooks:
      # Test critical math functions
      - id: test-options-math
        name: Test options math accuracy
        entry: pytest tests/test_options_properties.py -v
        language: system
        pass_filenames: false
        stages: [pre-push]

      # Verify configuration is valid
      - id: validate-config
        name: Validate configuration
        entry: python -c "import yaml; yaml.safe_load(open('config.yaml')); print('✓ Config valid')"
        language: system
        pass_filenames: false
