# Personal pre-commit configuration for single-developer Claude Code CLI workflow
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff formatter (replaces black)
        entry: ruff
        language: system
        types: [python]
        args: [format, --check]
      
      - id: ruff-lint
        name: Ruff linter (replaces black, isort, pyflakes, basic pylint)
        entry: ruff
        language: system
        types: [python]
        args: [check]
      
      - id: syntax-check
        name: Python syntax check
        entry: python3
        language: system
        files: \.py$
        args: [-m, py_compile]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict