# Minimal test configuration for validation
database:
  url: "data/test_validation.duckdb"
  
api:
  databento:
    enabled: false
  
storage:
  cache_dir: ".cache"
  
logging:
  level: "INFO"
  
hardware:
  cpu_cores: 8
  memory_gb: 19.2
