#!/bin/bash
# Safe Cleanup Commands - Generated by Agent 7
# Only removes cache, build artifacts, and regenerable files

set -e  # Exit on any error

echo 'Starting safe cleanup of disposable files...'

git rm --cached '.coverage 2' 2>/dev/null || true
git rm --cached '.coverage 3' 2>/dev/null || true
git rm --cached '.coverage 4' 2>/dev/null || true
git rm --cached '.coverage 5' 2>/dev/null || true
git rm --cached '.jarvis/experience.db' 2>/dev/null || true
git rm --cached '.jarvis/experience/experiences.db' 2>/dev/null || true
git rm --cached '.test_index/fts/code_fts.db' 2>/dev/null || true
git rm --cached '.test_index/kv/data.mdb' 2>/dev/null || true
git rm --cached '.test_index/kv/lock.mdb' 2>/dev/null || true
git rm --cached '.vscode/settings.json' 2>/dev/null || true
git rm --cached '.vscode/tasks.json' 2>/dev/null || true
git rm --cached '.wezterm-init.sh.backup' 2>/dev/null || true
git rm --cached 'jarvis2/.test_index/fts/code_fts.db' 2>/dev/null || true
git rm --cached 'jarvis2/.test_index/kv/data.mdb' 2>/dev/null || true
git rm --cached 'jarvis2/.test_index/kv/lock.mdb' 2>/dev/null || true
git rm --cached 'mcp-servers.json.backup' 2>/dev/null || true

echo 'Safe cleanup completed!'
echo 'Cleaned files:'
echo '  - .coverage 2'
echo '  - .coverage 3'
echo '  - .coverage 4'
echo '  - .coverage 5'
echo '  - .jarvis/experience.db'
echo '  - .jarvis/experience/experiences.db'
echo '  - .test_index/fts/code_fts.db'
echo '  - .test_index/kv/data.mdb'
echo '  - .test_index/kv/lock.mdb'
echo '  - .vscode/settings.json'
echo '  - .vscode/tasks.json'
echo '  - .wezterm-init.sh.backup'
echo '  - jarvis2/.test_index/fts/code_fts.db'
echo '  - jarvis2/.test_index/kv/data.mdb'
echo '  - jarvis2/.test_index/kv/lock.mdb'
echo '  - mcp-servers.json.backup'