# Cloud Run Job configuration for wheel trading recommendation engine
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: wheel-recommendation
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Use 2nd gen execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          serviceAccountName: wheel-trading-sa@PROJECT_ID.iam.gserviceaccount.com
          containers:
          - image: gcr.io/PROJECT_ID/wheel-recommendation:latest
            name: recommendation-engine
            resources:
              limits:
                cpu: "2"
                memory: "2Gi"
            env:
            # GCP configuration
            - name: GCP_PROJECT_ID
              value: "PROJECT_ID"
            - name: GCS_RAW_BUCKET
              value: "wheel-raw"
            - name: GCS_PROCESSED_BUCKET  
              value: "wheel-processed"
            
            # Credentials pulled from Secret Manager
            - name: WHEEL_SECRETS__USE_SECRET_MANAGER
              value: "true"
            
            # Optional overrides
            - name: WHEEL_STRATEGY__DELTA_TARGET
              value: "0.30"
            - name: WHEEL_RISK__MAX_POSITION_SIZE
              value: "0.20"
            
            # Job parameters (passed at runtime)
            - name: PORTFOLIO_VALUE
              valueFrom:
                configMapKeyRef:
                  name: job-params
                  key: portfolio_value
                  optional: true
            
            - name: ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: job-params
                  key: account_id
                  optional: true
          
          restartPolicy: Never
          timeoutSeconds: 300  # 5 minute timeout
---
# Service account with minimal permissions
apiVersion: iam.googleapis.com/v1
kind: ServiceAccount
metadata:
  name: wheel-trading-sa
  annotations:
    iam.gke.io/gcp-service-account: wheel-trading-sa@PROJECT_ID.iam.gserviceaccount.com
---
# Budget alert
apiVersion: monitoring.googleapis.com/v1
kind: BudgetAlert
metadata:
  name: wheel-trading-budget
spec:
  displayName: "Wheel Trading Monthly Budget"
  budgetAmount:
    specifiedAmount:
      currencyCode: "USD"
      units: "75"
  thresholdRules:
  - spendBasis: CURRENT_SPEND
    thresholdPercent: 0.9  # Alert at 90% of budget
  - spendBasis: CURRENT_SPEND  
    thresholdPercent: 1.0  # Alert at 100% of budget
  notificationsRule:
    schemaVersion: "1.0"
    monitoringNotificationChannels:
    - projects/PROJECT_ID/notificationChannels/YOUR_CHANNEL_ID