# Fast-fail CI checks that run in parallel
# Surfaces common failures quickly before running expensive tests

name: Fast Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Run all checks in parallel for fastest feedback
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Detect code changes to skip workflow on docs-only updates
  changes:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          code:
            - 'src/**'
            - 'tests/**'
            - 'pyproject.toml'
            - 'poetry.lock'
            - '.github/workflows/**'

  # Run all checks in parallel with no dependencies
  lint:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest  # Fallback from larger runners
    name: "Lint & Format"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure

  # Type checking removed - mypy no longer in dependencies

  # Security scanning removed - bandit no longer in dependencies
  # Security checks now handled by CodeQL in security.yml
