name: CI
# Fixed pip install -e . for proper package installation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install -e .

    - name: Run tests
      env:
        # Dummy values for CI
        DATABENTO_API_KEY: ci_test
      run: |
        pytest -v -m "not slow" --cov=src/unity_wheel

    - name: Check code quality
      run: |
        # Single tool for linting
        ruff check src/unity_wheel
