name: Personal Minimal Checks

# Minimal workflow for single-developer Claude Code CLI usage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff>=0.6.0
    
    - name: Code quality check (formatting + linting)
      run: |
        ruff format src tests --check --diff
        ruff check src tests
    
    - name: Import validation
      run: |
        python -c "
        import ast
        import glob
        import sys
        
        failed = False
        for file in glob.glob('src/**/*.py', recursive=True):
            try:
                with open(file, 'r') as f:
                    ast.parse(f.read())
            except SyntaxError as e:
                print(f'Syntax error in {file}: {e}')
                failed = True
            except Exception as e:
                print(f'Error parsing {file}: {e}')
                failed = True
        
        if failed:
            sys.exit(1)
        else:
            print('All Python files have valid syntax')
        "

  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'