# Optimized Security Scanning
name: Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 1 * * 1'  # Weekly on Monday

permissions:
  contents: read
  security-events: write

jobs:
  # Detect code changes to skip workflow on docs-only updates
  changes:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          code:
            - 'src/**'
            - 'tests/**'
            - 'pyproject.toml'
            - 'poetry.lock'
            - '.github/workflows/**'

  # CodeQL - Optimized for Python
  codeql:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging
    steps:
    - uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
        config-file: ./.github/codeql/codeql-config.yml
        # Use pre-compiled queries for speed
        queries: security-and-quality

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:python"
        upload: true
        # Only fail on high severity
        sarif-category-filter: "error"

  # Dependency scanning
  dependency-check:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install tools
      run: pip install safety bandit

    - name: Run Safety check
      run: |
        pip install poetry
        poetry export -f requirements.txt | safety check --stdin --json > safety-report.json || true

        # Parse results
        python -c "
        import json
        with open('safety-report.json') as f:
            data = json.load(f)
        vulns = data.get('vulnerabilities', [])
        if vulns:
            print(f'⚠️  Found {len(vulns)} vulnerabilities')
            for v in vulns[:5]:  # Show first 5
                print(f'  - {v[\"package\"]}: {v[\"vulnerability\"]}')
        else:
            print('✅ No known vulnerabilities')
        "

    - name: Run Bandit
      run: |
        bandit -r src/ -f json -o bandit-report.json || true

        # Parse results
        python -c "
        import json
        with open('bandit-report.json') as f:
            data = json.load(f)
        issues = data.get('results', [])
        high_issues = [i for i in issues if i['issue_severity'] == 'HIGH']
        if high_issues:
            print(f'⚠️  Found {len(high_issues)} high severity issues')
            for i in high_issues[:3]:
                print(f'  - {i[\"filename\"]}:{i[\"line_number\"]} - {i[\"issue_text\"]}')
        else:
            print('✅ No high severity issues')
        "

    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json

  # Secret scanning
  secret-scan:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for secret scanning

    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.63.2
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        extra_args: --debug --only-verified
